language: node_js
node_js:
  - "node"
before_install:
  - npm i -g aglio
script:
  - aglio -i apiary.apib --theme-template triple -o index.html
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET
  bucket: $AWS_BUCKET
  skip_cleanup: true
  region: $BUCKET_REGION
  acl: public_read
